apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: tech-challenge
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vdGMtcHNxbC1kYi5jMGd6Nm9nNXBheXgudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvc29hdA==
  SPRING_DATASOURCE_USERNAME: dGNhZG1pbg==
  SPRING_DATASOURCE_PASSWORD: VGNUZWNoMjAyNQ==
  MERCADO_PAGO_ACCESS_TOKEN: QVBQX1VTUi04MTA1NjQ2ODM3NjI4NDI0LTA0MjcxNC0wMjdiZjc2YzBjZmU1NzdhZDZiOTg3YjkwMTkwNDU2NC0yNDA0NjIxMDc5
  MERCADO_PAGO_POS: TE9KQTAxVFNUUE9TMDE=
  MERCADO_PAGO_USER_ID: MjQwNDYyMTA3OQ==
  MERCADO_PAGO_WEBHOOK_TOKEN: VGx2aEY0S0NHeU5wOUJRMmR3djN3Yk9ZVg==
  JWT_SECRET_KEY: c2VjcmV0Snd0R2VuZXJhdGlvblNvYXRUZWNoQ2hhbGxlbmdl
  BROKER_HOST: YnJva2VyLXNlcnZpY2UudGVjaC1jaGFsbGVuZ2U=
  BROKER_USERNAME: Z3Vlc3Q=
  BROKER_PASSWORD: Z3Vlc3Q=
